<a href="https://colab.research.google.com/github/aayushbokde/DL_study/blob/main/Embedding_in_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
docs =['go india',
'india india',
'hip hip hurray',
'jeetega bhai jeetega india jeetega',
'bharat mata ki jai',
'kohli kohli',
'sachin sachin',
'dhoni dhoni',
'modi ji ki jai'
'inquilab zindabad']

In [21]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

In [22]:
len(tokenizer.word_index)

17

In [23]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 1],
 [1, 1],
 [3, 3, 9],
 [2, 10, 2, 1, 2],
 [11, 12, 4, 13],
 [5, 5],
 [6, 6],
 [7, 7],
 [14, 15, 4, 16, 17]]

In [24]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 8,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3,  9,  0,  0],
       [ 2, 10,  2,  1,  2],
       [11, 12,  4, 13,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [14, 15,  4, 16, 17]], dtype=int32)

In [25]:
from keras.models import Sequential
from keras.layers import Dense,Flatten,Embedding
model = Sequential()
model.add(Embedding(18, output_dim=2, input_length=5))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile('adam','accuracy')

In [27]:

pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
[[[-0.011858   -0.02714365]
  [-0.04955732 -0.0315192 ]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]]

 [[-0.04955732 -0.0315192 ]
  [-0.04955732 -0.0315192 ]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]]

 [[ 0.02454189 -0.00116619]
  [ 0.02454189 -0.00116619]
  [-0.04437082  0.01440943]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]]

 [[ 0.0280936   0.00214209]
  [-0.00045209  0.00394624]
  [ 0.0280936   0.00214209]
  [-0.04955732 -0.0315192 ]
  [ 0.0280936   0.00214209]]

 [[-0.04068922  0.01453911]
  [-0.04385839 -0.00138831]
  [-0.00288519  0.04121885]
  [ 0.03658289 -0.00906073]
  [ 0.04652527  0.02646839]]

 [[ 0.04972665 -0.00423106]
  [ 0.04972665 -0.00423106]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.02646839]]

 [[ 0.03589955  0.00157434]
  [ 0.03589955  0.00157434]
  [ 0.04652527  0.02646839]
  [ 0.04652527  0.0264683